# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 00:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='secret',
        ),
        migrations.AlterField(
            model_name='address',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 0, 52, 46, 483131, tzinfo=utc)),
        ),
    ]
