# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 03:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0005_auto_20180626_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='secret',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 3, 22, 8, 297793, tzinfo=utc)),
        ),
    ]
