# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 03:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0006_auto_20180626_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='secret',
        ),
        migrations.AlterField(
            model_name='address',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 3, 37, 51, 134135, tzinfo=utc)),
        ),
    ]
