# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0008_auto_20180626_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='secret_addr',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 4, 22, 18, 440525, tzinfo=utc)),
        ),
    ]
