# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 06:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('addr', '0012_auto_20180626_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 26, 6, 16, 22, 655496, tzinfo=utc)),
        ),
    ]
